### ISSUE TITLE
Tests fail because of index size problem and schema check

### ISSUE THREAD

**Issue by murithigeo** [opengeospatial/ets-ogcapi-edr10#133]
**Describe the bug**
Several tests are failing and no idea why

**Expected behavior**
Better error messages?

**Screenshots**
![Screenshot (86)](https://github.com/user-attachments/assets/9cb8a378-bc60-47cb-b39b-d64b6ed3687d)

**Additional context**
[s0013.zip](https://github.com/user-attachments/files/17134673/s0013.zip)

Additionally, it fails on collections even though there is a locations queryType supported on the collection metadata.

**Comment by dstenger** [comment]
Thank you for reporting.

A possible cause might be that your service contains CRS with height (it must be checked if those are supported by the test suite): http://www.opengis.net/def/crs/OGC/0/CRS84h
I agree that the error message is not readable and should be improved.

We will do further investigation and provide additional feedback.
For better reproduction, is it possible to provide a public API we can use for testing?

**Comment by dstenger** [comment]
@murithigeo There are two error messages in your screenshot, can you please create a separate issue for the second message?
We prefer to just cover one error/question per issue.

**Comment by murithigeo** [comment]
> A possible cause might be that your service contains CRS with height (it must be checked if those are supported by the test suite): http://www.opengis.net/def/crs/OGC/0/CRS84h

I'm only using CRS84. This is the collections metadata document
```yaml
collections:
  - id: hourlyWeather
    crs:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
    output_formats:
      - GEOJSON
      - COVERAGEJSON
    title: hourlyWeather collection
    keywords:
      - noaa
      - temperature
    extent:
      spatial:
        bbox:
          - - -17.490225
            - -49.35
            - 70.25
            - 36.851033
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        interval:
          - - '2023-12-31T21:00:00.000Z'
            - '2024-05-13T18:30:00.000Z'
        trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
      vertical:
        name: MSL_Height
        interval:
          - -15
          - 2480
        vrs: http://www.opengis.net/def/crs/EPSG/0/5714
```
